version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "4000:80"

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        - SA_PASSWORD=pass_1254a
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"